-- Expand the data model


DROP TABLE "DT"."RENT_CARS"
;
DROP TABLE "DT"."RENTALS"
;

  CREATE TABLE "DT"."RENT_CARS" 
   ("VIN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MAKE" VARCHAR2(20 BYTE), 
	"MODEL" VARCHAR2(20 BYTE), 
	"MODEL_YEAR" NUMBER(4,0), 
	"MILEAGE" NUMBER(10,0), 
	"COLOR" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(2 BYTE), 
	"TAG" VARCHAR2(20 BYTE), 
	"IN_OUT" CHAR(1 BYTE), 
	 CONSTRAINT "RENT_CARS_PK" PRIMARY KEY ("VIN")
 )
 ;

Insert into RENT_CARS (VIN,MAKE,MODEL,MODEL_YEAR,MILEAGE,COLOR,STATE,TAG,IN_OUT) values ('CIPZCO831SFCQ2RU1','Ford','Fusion',2016,8373,'Blue','TX','QWE-123','I');
Insert into RENT_CARS (VIN,MAKE,MODEL,MODEL_YEAR,MILEAGE,COLOR,STATE,TAG,IN_OUT) values ('YLWDMZU5DWMHAMUR5','Ford','Focus',2016,34,'Green','CO','AB-3443','O');
Insert into RENT_CARS (VIN,MAKE,MODEL,MODEL_YEAR,MILEAGE,COLOR,STATE,TAG,IN_OUT) values ('U9HZ2CY4QQ624WX7A','Nissan','Sentra',2017,12343,'Red','CA','5-9333S','I');
Insert into RENT_CARS (VIN,MAKE,MODEL,MODEL_YEAR,MILEAGE,COLOR,STATE,TAG,IN_OUT) values ('X3HPHVLMUZVYTXAL7','Toyota','Camry',2017,2134,'White','TX','ABC-321','I');
COMMIT;

  CREATE TABLE "DT"."RENTALS" 
   ("RENTAL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DT_OUT" DATE, 
	"DT_RETURN" DATE, 
	"VIN" VARCHAR2(20 BYTE), 
	 CONSTRAINT "RENTALS_PK" PRIMARY KEY ("RENTAL_ID")
  )
;

REM INSERTING into RENTALS
SET DEFINE OFF;
INSERT INTO RENTALS VALUES (1, TO_DATE('2017-04-03', 'YYYY-MM-DD'), TO_DATE('2017-04-10', 'YYYY-MM-DD'), 'YLWDMZU5DWMHAMUR5');
INSERT INTO RENTALS VALUES (2, TO_DATE('2017-04-12', 'YYYY-MM-DD'), TO_DATE('2017-04-17', 'YYYY-MM-DD'), 'YLWDMZU5DWMHAMUR5');
INSERT INTO RENTALS VALUES (3, TO_DATE('2017-03-01', 'YYYY-MM-DD'), TO_DATE('2017-03-13', 'YYYY-MM-DD'), 'X3HPHVLMUZVYTXAL7');
COMMIT;
